services:
  - type: web
    name: aso-split-pro
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-por
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
